### ISSUE TITLE
Broken "rpg_series:tier_2_accessories" Tag due to Unnecessary Underscore. 

### ISSUE THREAD

**Issue by InputandOutput** [ProfessorFichte/Additional-RPG-Jewelry#3]
Hello Fichte, 
Looking through the logs (and with the help of Load my F***ing Tags mod), the tag "rpg_series:tier_2_accessories" seems to be broken for the accessories in your mod. Looking into your mod shows that the /data/rpg_series/tags/item/tier_2_accessories.json file contains an array with probably mistyped entries, as shown in the log snippet below:

`[10:10:19] [Worker-Main-10/ERROR]: [Load My F***ing Tags] Couldn't load certain entries with the tag rpg_series:tier_2_accessories: additional_rpg_jewelry:_earth_ring (from additional_rpg_jewelry), additional_rpg_jewelry:_earth_necklace (from additional_rpg_jewelry), additional_rpg_jewelry:_ocean_ring (from additional_rpg_jewelry), additional_rpg_jewelry:_ocean_necklace (from additional_rpg_jewelry), additional_rpg_jewelry:_sky_ring (from additional_rpg_jewelry), additional_rpg_jewelry:_sky_necklace (from additional_rpg_jewelry), additional_rpg_jewelry:_rage_ring (from additional_rpg_jewelry), additional_rpg_jewelry:_rage_necklace (from additional_rpg_jewelry)`

The fix is simple, as just removing the extra underscore (e.g. additional_rpg_jewelery:_earth_ring -> additional_rpg_jewelery:earth_ring") with a replacement datapack seems to solve the issue. The broken tag does result in the affected items not inheriting the tag mentioned previously as broken compatibility, however.

**Comment by ProfessorFichte** [comment]
Thanks for reporting the issue, I  will fix it in the next update :)

**Comment by ProfessorFichte** [comment]
Fixed with newest version for both 1.20.1 & 1.21
