### ISSUE TITLE
Mipmap texture issue

### ISSUE THREAD

**Issue by xR4YM0ND** [ProfessorFichte/Additional-RPG-Jewelry#5]
`[Worker-ResourceReload-6/WARN]: Texture additional_rpg_jewelry:item/griffin_school_medallion with size 12x12 limits mip level from 3 to 2`
Pls change this texture to 16x16 , 32x32 or so on

**Comment by ProfessorFichte** [comment]
Thanks for reporting the issue @xR4YM0ND !
Fixed with versions:
2.0.3 - 1.21.1 & 1.21
1.0.9 - 1.20.1
Uploaded the new versions on Curseforge & Modrinth, should be available soon.

**Comment by xR4YM0ND** [comment]
Danke dir! <3
